CREATE TABLE VBMSUI.CONTENTION_EVENT_LATEST (
    ActionName VARCHAR(4000),
    ActionResultName VARCHAR(4000),
    ActorUserId VARCHAR(4000),
    ActorApplicationId VARCHAR(4000),
    ActorStation VARCHAR(4000),
    AutomationIndicator NUMBER(1),
    BenefitClaimTypeCode VARCHAR(4000),
    ClaimId NUMBER(18),
    ContentionClassificationName VARCHAR(4000),
    ContentionId NUMBER(18),
    ContentionStatusTypeCode VARCHAR(4000),
    ContentionTypeCode VARCHAR(4000),
    CurrentLifecycleStatus VARCHAR(4000),
    DateAdded DATE,
    Details VARCHAR(4000),
    DiagnosticTypeCode VARCHAR(4000),
    EventTime DATE,
    JournalStatusTypeCode VARCHAR(4000),
    VeteranParticipantId NUMBER(18),
    CONSTRAINT pk_contention_id PRIMARY KEY(ContentionId)
);